### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by raulfdm** [kennethormandy/react-flipcard#1]
https://github.com/kennethormandy/react-flipcard/blob/0e062f45f29dd9e63f584f5d1190f719c6863448/package.json#L7

Why this rule? I'm actually using v8.9.1 and I cannot install because there is this specification.

**Comment by kennethormandy** [comment]
Oh, that’s the minimum version I’m using, so that’s why I include it. It’s an easy change if it’s negatively impacting thing install, but I would have expected it to not do anything on higher versions. What is the error or warning message you’re getting? Thanks for opening an issue :)

**Comment by kennethormandy** [comment]
For what it’s worth, the only warning message I get running `npm install @kennethormandy/react-flipcard` on Node v8.9.4 is the expected React peerDependency warning:

```sh
npm WARN @kennethormandy/react-flipcard@0.4.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
```

Happy to investigate this further, with more info, though. Perhaps it should just be `>=6.10` instead.

**Comment by kennethormandy** [comment]
Even though I couldn’t reproduce the error, upon reviewing [the engines documentation](https://docs.npmjs.com/files/package.json#engines), it made sense to make this more forgiving. Hope that works for you too @raulfdm, and thanks again.
